### ISSUE TITLE
Etching Mask

### ISSUE THREAD

**Issue by AGenews** [open-ephys/flexDrive#10]
Hi,
I plan to play a little bit and find a way to etch those springs. Unfortunately I am bound to Linux and Freecad refuses to open any of the provided files properly. So could you upload a *.SVG* or even a KiCAD file with the outlines of the spring?
Thanks + Best,
Andreas

**Comment by jvoigts** [comment]
Hi, just re-exported this as DXF DWG and PDF ( dea8cec32c9d1df16cb5ae3bcf781cfb7e4ea197 ), i think that's the closest i can get with solidworks here. That said, if you have a few months to spare before you need the drives, maybe hold off on this. I might have an updated design ready then that does not require a spring at all.

**Comment by AGenews** [comment]
Thanks a lot!
